FROM docker.io/ubuntu:latest 

# Install dependencies
RUN apt-get update -y && apt-get install -y pip
RUN apt install -y python3-etcd3

# PYTHON:

# Install python and other dependencies
RUN apt-get install -y python3

# Install Antithesis Python SDK
RUN pip install antithesis cffi --break-system-packages

# Copying python entrypoint. It contains the lifecycle setup_complete message.
COPY ./entrypoint/entrypoint.py /entrypoint.py