version: '3.8'

services:

  etcd0:
    image: 'docker.io/bitnami/etcd:3.5'
    container_name: etcd0
    hostname: etcd0
    # user: root
    environment: 
      ETCD_NAME: "etcd0"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd0:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd0.etcd:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster-1"
      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ALLOW_NONE_AUTHENTICATION: "yes"
    networks:
      antithesis-net:
        ipv4_address: 10.0.0.10

  etcd1:
    image: 'docker.io/bitnami/etcd:3.5'
    container_name: etcd1
    hostname: etcd1
    # user: root
    environment: 
      ETCD_NAME: "etcd1"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd1:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd1.etcd:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster-1"
      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ALLOW_NONE_AUTHENTICATION: "yes"
    networks:
      antithesis-net:
        ipv4_address: 10.0.0.15

  etcd2:
    image: 'docker.io/bitnami/etcd:3.5'
    container_name: etcd2
    hostname: etcd2
    # user: root
    environment: 
      ETCD_NAME: "etcd2"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd2:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd2.etcd:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster-1"
      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ALLOW_NONE_AUTHENTICATION: "yes"
    networks:
      antithesis-net:
        ipv4_address: 10.0.0.20

  client:
    image: 'us-central1-docker.pkg.dev/molten-verve-216720/demo-repository/etcd-client:latest'
    container_name: client
    # TODO: add env var for output (to capture setup_complete)
    networks:
      antithesis-net:
        ipv4_address: 10.0.0.131
    user: root
    entrypoint: ['/entrypoint.py']


networks:
  antithesis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
